apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: db-pvc4
  namespace: db-ns4
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2Gi